"""
Post-install setup for Oh My Codex.
Run with: omx-setup
"""
from __future__ import annotations

import os
import sys
import shutil
import urllib.request
import zipfile
import tempfile
from pathlib import Path

REPO_URL = "https://github.com/junghwaYang/oh-my-codex"
SKILLS_URL = f"{REPO_URL}/archive/refs/heads/main.zip"


def get_codex_dir() -> Path:
    """Get the Codex configuration directory."""
    return Path.home() / ".codex"


def print_step(msg: str, emoji: str = "→") -> None:
    """Print a setup step."""
    print(f"  {emoji} {msg}")


def setup_directories() -> None:
    """Create required directories."""
    codex_dir = get_codex_dir()
    dirs = [
        codex_dir,
        codex_dir / "skills",
        codex_dir / "sessions",
        codex_dir / "plans",
        codex_dir / "errors",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


def setup_billing() -> str:
    """Interactive billing setup."""
    print("\n💳 Billing Setup\n")
    print("  How do you want to use Codex?\n")
    print("  1) Codex Pro - $200/month subscription (unlimited)")
    print("  2) OpenAI API - Pay per token (usage-based)\n")
    
    try:
        choice = input("  Select [1/2]: ").strip()
    except (EOFError, KeyboardInterrupt):
        choice = "1"
    
    if choice == "2":
        return "openai"
    return "codex"


def setup_config(provider: str) -> None:
    """Create or update config.toml."""
    config_path = get_codex_dir() / "config.toml"
    
    config_content = f'''# Oh My Codex Configuration
# Generated by omx-setup

[model]
default = "gpt-5.1-codex"

[model.routing]
nano = "gpt-5-nano"
mini = "gpt-5-mini"
standard = "gpt-5.1-codex"
powerful = "gpt-5.2-codex"
max = "gpt-5.1-codex-max"

[model.reasoning]
default = "none"
eco = "none"
plan = "medium"
autopilot = "high"
ultrawork = "medium"
ultrapilot = "xhigh"
ralph = "xhigh"
review = "high"
debug = "xhigh"

[billing]
provider = "{provider}"

[skills]
auto_load = true

[compaction]
enabled = true
threshold_tokens = 100000
'''
    
    if config_path.exists():
        backup = config_path.with_suffix(".toml.bak")
        shutil.copy(config_path, backup)
        print_step(f"Backed up existing config to {backup.name}")
    
    config_path.write_text(config_content)
    print_step(f"Created config at {config_path}")


def download_skills() -> None:
    """Download and install skills from GitHub."""
    skills_dir = get_codex_dir() / "skills"
    
    print_step("Downloading skills from GitHub...")
    
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            zip_path = Path(tmpdir) / "repo.zip"
            
            # Download the repo
            urllib.request.urlretrieve(SKILLS_URL, zip_path)
            
            # Extract
            with zipfile.ZipFile(zip_path, 'r') as zf:
                zf.extractall(tmpdir)
            
            # Find the skills directory
            extracted_dir = Path(tmpdir) / "oh-my-codex-main" / ".codex" / "skills"
            
            if extracted_dir.exists():
                # Copy each skill
                count = 0
                for skill_dir in extracted_dir.iterdir():
                    if skill_dir.is_dir():
                        dest = skills_dir / skill_dir.name
                        if dest.exists():
                            shutil.rmtree(dest)
                        shutil.copytree(skill_dir, dest)
                        count += 1
                
                print_step(f"Installed {count} skills to {skills_dir}", "✅")
            else:
                print_step("Skills directory not found in download", "⚠️")
                
    except Exception as e:
        print_step(f"Failed to download skills: {e}", "❌")
        print_step("You can manually clone the repo and run install.sh")


def download_agents_md() -> None:
    """Download AGENTS.md template."""
    try:
        url = f"{REPO_URL}/raw/main/AGENTS.md"
        agents_path = get_codex_dir() / "AGENTS.md"
        
        urllib.request.urlretrieve(url, agents_path)
        print_step(f"Downloaded AGENTS.md to {agents_path}", "✅")
    except Exception as e:
        print_step(f"Failed to download AGENTS.md: {e}", "⚠️")


def check_codex_cli() -> bool:
    """Check if Codex CLI is installed."""
    return shutil.which("codex") is not None


def main() -> None:
    """Main setup entry point."""
    print("\n🚀 Oh My Codex Setup\n")
    
    # Check Codex CLI
    if not check_codex_cli():
        print("⚠️  Codex CLI not found. Install it first:")
        print("   npm install -g @openai/codex")
        print("   or: brew install --cask codex\n")
    
    # Create directories
    print("📁 Setting up directories...")
    setup_directories()
    print_step("Created ~/.codex/ structure", "✅")
    
    # Billing setup
    provider = setup_billing()
    
    # Create config
    print("\n⚙️  Setting up configuration...")
    setup_config(provider)
    
    # Download skills
    print("\n📦 Installing skills...")
    download_skills()
    
    # Download AGENTS.md
    print("\n📝 Setting up AGENTS.md...")
    download_agents_md()
    
    # Done
    print("\n" + "=" * 50)
    print("✅ Oh My Codex setup complete!\n")
    print("Usage:")
    print('  omx "autopilot: build a REST API"')
    print('  omx "ulw: refactor all files"')
    print('  omx "eco: quick fix"')
    print('  omx --status')
    print("\nDocs: https://github.com/junghwaYang/oh-my-codex")
    print()


if __name__ == "__main__":
    main()
